apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: image
    app.kubernetes.io/instance: image-sample
    app.kubernetes.io/part-of: garm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: garm-operator
  name: runner-default
  namespace: garm-operator-system
spec:
  tag: default-runner:linux-ubuntu-22.04-amd64-main-e4de304
