## Append samples of your project ##
resources:
  - garm-operator_v1alpha1_enterprise.yaml
  - garm-operator_v1alpha1_pool.yaml
  - garm-operator_v1alpha1_organization.yaml
  - garm-operator_v1alpha1_image.yaml
  - garm-operator_v1alpha1_repository.yaml
  - garm-operator_v1alpha1_runner.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
