garm:
  username: "garm-username"
  password: "garm-password"
  server: "http://garm-server:9997"

operator:
  metrics_bind_address: ":7000"
  health_probe_bind_address: ":7001"
  leader_election: true
  sync_period: "10m"
  namespace: "garm-operator-namespace"
  create_webhook: false
